[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/wisuda.usbypkp.ac.id/aplikasi-absensi-wisuda/artisan queue:work --sleep=3 --tries=3 --timeout=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/wisuda.usbypkp.ac.id/aplikasi-absensi-wisuda/storage/logs/worker.log
stopwaitsecs=3600
